### ISSUE TITLE
How to colaborate?

### ISSUE THREAD

**Issue by ruvasqm** [andrew-rosario/universal-exercise-file#1]
I have some ideas:
- Descriptors for muscles engaged
- Positions and joints
- Weights direction

Honestly it is all fuzzy but I wanted to make this so why not work together?

**Comment by andrew-rosario** [comment]
Hey Rubén, this was just a random idea I made in my CS undergrad. Maybe I'll get started on it someday, but it's not something I'm really interested in working on right now.

(I am honestly stunned you even found this repository in the first place.)

You can totally just make a new repo and just make the file format on your own.

**Comment by ruvasqm** [comment]
I've got other projects atm, I was kinda hoping to spark your interest again xD

Thank you for the response, good luck!
